jupyter_book_task:
  env:
    JULIA_VER: "1.8.0"
    JULIA_NUM_THREADS: "4"
    LC_ALL: "C"
  auto_cancellation: true
  container:
    image: python:3.10-slim
    cpu: 4
    memory: 16G
    use_in_memory_disk: true
  syspkg_script: apt-get update -q && apt-get install -qqy git parallel wget
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && cat .ci/requirements.txt
  python_packages_script: |
    pip install -r .ci/requirements.txt
  install_julia_script: |
    wget https://raw.githubusercontent.com/abelsiqueira/jill/main/jill.sh
    bash jill.sh --version ${JULIA_VER} --yes
    julia --version
  jupkg_cache:
    folder: ~/.julia
    fingerprint_script: cat Manifest.toml
  julia_packages_script: |
    julia --color=yes --project=@. -e 'import Pkg; Pkg.instantiate(); Pkg.build("IJulia")'
  notebook_script: |
    parallel -j4 jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --execute --inplace {} ::: docs/*.ipynb
  build_script: |
    jupyter-book build docs --warningiserror --keep-going -v

  # pages_script: |
  #   if [[ $CIRRUS_BRANCH == "main" ]]; then
  #     ghp-import -n docs/_build/html
  #     git push -fq https://${GH_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git gh-pages
  #   fi
